### ISSUE TITLE
No such file or directory: '/usr/local/lib/python3.6/dist-packages/htmlc/data/c_code/boolean.h'

### ISSUE THREAD

**Issue by timostrating** [HTML-as-programming-language/HTML-as-programming-language#24]
## Expected Behavior
$ cd /HTML-as-programming-language/working-code 
$ htmlc serial.html 

## Actual Behavior
Traceback (most recent call last):
  File "/usr/local/bin/htmlc", line 11, in <module>
    load_entry_point('HTML-as-programming-language==0.1.19', 'console_scripts', 'htmlc')()
  File "/usr/local/lib/python3.6/dist-packages/htmlc/compiler.py", line 163, in main
    saved_to_c = compiler.save_to_c_file()
  File "/usr/local/lib/python3.6/dist-packages/htmlc/compiler.py", line 81, in save_to_c_file
    self.c_linker.save_htmlc_files(outdir)
  File "/usr/local/lib/python3.6/dist-packages/htmlc/c_linker.py", line 53, in save_htmlc_files
    pkg_resources.resource_string(__name__, "data/c_code/" + hi)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1149, in resource_string
    self, resource_name
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1393, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1516, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/htmlc/data/c_code/boolean.h'

## Steps to Reproduce the Problem

  1. $ pip install HTML-as-programming-language
  2. $ cd /HTML-as-programming-language/working-code 
  3. $ htmlc serial.html 

## Specifications
De data folder wordt niet mee gedownload met pip install HTML-as-programming-language

sneeuwpop @ /usr/local/lib/python3.6/dist-packages/htmlc - [] $ ls
c_linker.py  code_range.py  compiler.py  diagnostics.py  elements/  gcc/  html_parser.py  __init__.py  json_rpc.py  lang_server.py  lexer.py  linker.py  mapped_c_string.py  __pycache__/  utils.py

  - Version: HTML-as-programming-language==0.1.19
  - Platform: linux

**Comment by hilkojj** [comment]
Bug confirmed in version 0.1.19

I forgot to upload the newest version (0.1.20) to PyPi.
Try to install version 0.1.20 and try again
